language: php
php:
  - 5.6
  - 7.0

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "fxp/composer-asset-plugin:*"
  - composer global require "codeception/codeception:~2.1"
  - composer update

script:
  - codecept build
  - codecept run

notifications:
  email: false
