language: php
php:
  - 5.5
  - 5.6

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require "fxp/composer-asset-plugin:*"
  - composer global require "codeception/codeception:*"
  - composer update

script:
  - codecept build
  - codecept run

notifications:
  email: false
